--- 
output_dir: output
data_sources: 
- type: filesystem_unified
  items_root: /
  layouts_root: /

# Custom settings

# Use rsync + ssh for live site. To deploy:
#
#   % rake deploy:rsync
deploy:
  default:
    dst: "intothes@intothespirit.com:/home6/intothes/www/itsv5"
    options: ['-ave ssh', '--exclude=.DS_Store', '--exclude=.git', '--exclude=.rvmrc', '--exclude=*~']

# domain to which this site is deployed
base_url: http://intothespirit.com

google_analytics:
  domain: intothespirit.com
  site_id: UA-7162223-2

# currently used by logo
site_name: intothespirit.com

# number of full featured posts to display on front
featured_count: 0

# number of excerpted posts to display on front
excerpt_count: 6

# number of other articles to reference at bottom of each article
other_articles_max: 3

# DISQUS Site Shortname. Comment out to disable.
#disqus_shortname: nanoc3-blog

